workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          flutter pub get
          mkdir -p ios/Flutter
          mkdir -p assets/images
          
      - name: Fix Podfile
        script: |
          # Perbaiki Podfile dengan mengubah **FILE** menjadi __FILE__
          sed -i '' 's/\*\*FILE\*\*/__FILE__/g' ios/Podfile
          
          # Buat script Ruby untuk memperbaiki flutter_root path
          cat > ios/fix_podfile.rb << 'EOFRUBY'
          #!/usr/bin/env ruby
          podfile_content = File.read('Podfile')
          flutter_path = `which flutter`.strip
          flutter_bin_dir = File.dirname(flutter_path)
          flutter_root = File.dirname(flutter_bin_dir)
          new_content = podfile_content.gsub(/def flutter_root.*?end/m, "def flutter_root\n  \"#{flutter_root}\"\nend")
          File.write('Podfile', new_content)
          puts "Fixed Podfile with flutter_root: #{flutter_root}"
          EOFRUBY
          
          # Jalankan script Ruby untuk memperbaiki Podfile
          cd ios
          ruby fix_podfile.rb
          
          echo "Podfile setelah perbaikan:"
          cat Podfile
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          
      - name: Build iOS app
        script: |
          # Build iOS app dengan flag no-tree-shake-icons
          flutter build ios --release --no-codesign --no-tree-shake-icons
          
      - name: Create IPA file
        script: |
          # Buat struktur direktori Payload
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          
          # Arsipkan sebagai IPA
          zip -r Runner.ipa Payload
          
          # Pindahkan ke lokasi yang mudah diakses
          mkdir -p ../../ipa
          cp Runner.ipa ../../ipa/
          
          echo "IPA file created at build/ios/ipa/Runner.ipa"
          
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/Runner.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com  # Ganti dengan email Anda