workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          flutter pub get
          mkdir -p ios/Flutter
          
      - name: Fix Podfile with Ruby
        script: |
          cd ios
          chmod +x fix_podfile.rb
          ruby fix_podfile.rb
          cat Podfile
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/**/outputs/**/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log