workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          # Pastikan flutter pub get dijalankan dengan benar
          flutter pub get
          # Verifikasi dan buat direktori yang dibutuhkan
          ls -la ios/
          mkdir -p ios/Flutter/
          # Pastikan Generated.xcconfig dibuat
          test -f ios/Flutter/Generated.xcconfig || flutter pub get
          
      - name: Install CocoaPods dependencies
        script: |
          # Pastikan flutter pub get dijalankan kembali untuk menghasilkan file konfigurasi
          flutter pub get
          # Verifikasi isi Podfile sebelum pod install
          cat ios/Podfile
          # Kemudian baru masuk ke direktori iOS untuk pod install
          cd ios
          pod install --repo-update
          
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/**/outputs/**/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - herman.sama52@gmail.com
